### ISSUE TITLE
Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by KenWuqianghao** [radioactive11/apple-music-readme#1]
I'm fairly certain I have acquired the correct environment variables so but I got the following error. If it would be possible to set up an meeting to debug this that would be great.
<img width="1512" alt="Screenshot 2022-12-18 at 03 14 16" src="https://user-images.githubusercontent.com/20444505/208288117-13489460-aba0-41f7-9ff5-0727f3febb0a.png">

**Comment by radioactive11** [comment]
Sure @KenWuqianghao! Can we meet around 4:00 PM IST (around 2 hours from now)?

**Comment by KenWuqianghao** [comment]
Nah its 3 am in Canada right now, maybe 10am IST?

**Comment by radioactive11** [comment]
10 AM IST (19 Dec) works for me

**Comment by KenWuqianghao** [comment]
great, see u then

**Comment by radioactive11** [comment]
> great, see u then

Is a Google Meet fine?

**Comment by KenWuqianghao** [comment]
yeah sounds good

**Comment by radioactive11** [comment]
> yeah sounds good

I have sent you an invite link via email

**Comment by radioactive11** [comment]
Fixed via [this commit](https://github.com/radioactive11/apple-music-readme/commit/3d8d93c7a6c40c1c7db928d098897326fd0f3202)
