### ISSUE TITLE
& is breaking my songs' card 😡

### ISSUE THREAD

**Issue by radhikakakkar** [radioactive11/apple-music-readme#3]
Hi friend, the code is great!
Although for some of my songs with multiple artists, the card was not rendering properly. I did you a fix, please merge 🥰.

**Comment by radioactive11** [comment]
Hi @radhikakakkar 
Thank you for taking out time to fix the issue. Also glad you liked the project.

Feel free to raise a PR and attach screenshots of before and after the fix. 

Thank you once again ❤️

**Comment by radioactive11** [comment]
Resolved in #4
